using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BookStudio.Application.Authoring;
using Microsoft.Data.Sqlite;

namespace BookStudio.Infrastructure.Persistence.Sqlite.Research;

public sealed class SqliteClaimVerificationStore : IClaimVerificationStore, IAsyncDisposable
{
    private readonly SqliteConnectionFactory _factory;
    private readonly SqliteWriteQueue _queue;
    private int _disposed;

    public SqliteClaimVerificationStore(SqliteConnectionFactory factory, int capacity = 64)
    {
        _factory = factory ?? throw new ArgumentNullException(nameof(factory));
        _queue = new SqliteWriteQueue(factory, capacity);
    }

    public ValueTask<ClaimVerificationCreateResult> CreateAsync(ClaimVerificationDraft d, DateTimeOffset at, CancellationToken ct = default)
    {
        ValidateDraft(d);
        var hash = Hash(JsonSerializer.Serialize(d));
        return _queue.ExecuteInTransactionAsync((c, tx, token) =>
        {
            token.ThrowIfCancellationRequested();
            var existing = Read(c, tx, d.WorkspaceId, d.VerificationId);
            if (existing is not null)
            {
                var receipt = ReadReceipt(c, tx, d.WorkspaceId, d.VerificationId) ?? throw new ClaimVerificationConflictException("Create receipt missing.");
                RequireReceipt(receipt, "CREATE", d.WorkspaceId, d.VerificationId, d.RequestFingerprint, hash);
                return new ClaimVerificationCreateResult(existing, true);
            }
            RequireAuthority(c, tx, d.WorkspaceId, d.ProjectId, d.ResearchPlanId, d.ExpectedResearchPlanRevision, d.ExpectedResearchPlanDigest);
            var message = MessageId(d.VerificationId);
            Execute(c, tx, "INSERT INTO claim_verifications(workspace_id,verification_id,project_id,research_plan_id,expected_research_plan_revision,expected_research_plan_digest,claim_id,claim_type,location,version,rule_set,actor,snapshot_json,revision,status,decision,decision_reason,expected_research_revision,message_id,created_at_utc,updated_at_utc) VALUES($w,$id,$p,$plan,$r,$digest,$claim,$type,$location,$v,$rules,$actor,$snapshot,1,'PROPOSED',NULL,NULL,NULL,$m,$at,$at);", ("$w", d.WorkspaceId), ("$id", d.VerificationId.ToString("D")), ("$p", d.ProjectId.ToString("D")), ("$plan", d.ResearchPlanId.ToString("D")), ("$r", d.ExpectedResearchPlanRevision), ("$digest", d.ExpectedResearchPlanDigest), ("$claim", d.ClaimId.ToString("D")), ("$type", d.ClaimType.ToString().ToUpperInvariant()), ("$location", d.Location), ("$v", d.Version), ("$rules", d.RuleSet), ("$actor", d.Actor), ("$snapshot", d.SnapshotJson), ("$m", message.ToString("D")), ("$at", Text(at)));
            InsertHistory(c, tx, d.WorkspaceId, d.VerificationId, 1, "CREATE", d.Actor, null, new { d.ClaimId, d.ClaimType, d.Location }, at);
            InsertReceipt(c, tx, d.WorkspaceId, d.VerificationId, d.VerificationId, "CREATE", d.RequestFingerprint, hash, 1, message, at);
            InsertOutbox(c, tx, message, "claim.verification.proposed", new { d.WorkspaceId, d.VerificationId, d.ProjectId, d.ClaimId, d.Actor }, at);
            return new ClaimVerificationCreateResult(Require(c, tx, d.WorkspaceId, d.VerificationId), false);
        }, ct);
    }

    public ValueTask<ClaimVerification> EvaluateAsync(ClaimVerificationEvaluateCommand cmd, DateTimeOffset at, CancellationToken ct = default)
    {
        ValidateEvidence(cmd.Evidence);
        if (string.IsNullOrWhiteSpace(cmd.EvaluationNote)) throw new ClaimVerificationValidationException("Evaluation note is required.");
        return Mutate(cmd.RequestId, cmd.WorkspaceId, cmd.VerificationId, "EVALUATE", cmd.RequestFingerprint, Hash(JsonSerializer.Serialize(cmd)), cmd.ExpectedRevision, at, (c, tx, item) =>
        {
            if (!AuthorityMatches(c, tx, item)) return MarkStaleCore(c, tx, item, cmd.RequestId, "Research plan authority drift.", cmd.Actor, at);
            if (item.Status is ClaimVerificationStatus.Verified or ClaimVerificationStatus.Refuted or ClaimVerificationStatus.Stale) throw new ClaimVerificationTransitionException("Verification cannot be evaluated from its current state.");
            ReplaceEvidence(c, tx, item.WorkspaceId, item.VerificationId, cmd.Evidence);
            return Advance(c, tx, item, ClaimVerificationStatus.Evaluated, cmd.RequestId, "EVALUATE", cmd.Actor, cmd.EvaluationNote, new { EvidenceCount = cmd.Evidence.Count }, "claim.verification.evaluated", at);
        }, ct);
    }

    public ValueTask<ClaimVerification> DecideAsync(ClaimVerificationDecisionCommand cmd, DateTimeOffset at, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(cmd.Reason)) throw new ClaimVerificationValidationException("Decision reason is required.");
        return Mutate(cmd.RequestId, cmd.WorkspaceId, cmd.VerificationId, "DECIDE", cmd.RequestFingerprint, Hash(JsonSerializer.Serialize(cmd)), cmd.ExpectedRevision, at, (c, tx, item) =>
        {
            if (!AuthorityMatches(c, tx, item)) return MarkStaleCore(c, tx, item, cmd.RequestId, "Research plan authority drift.", cmd.Actor, at);
            if (item.Status != ClaimVerificationStatus.Evaluated) throw new ClaimVerificationTransitionException("Only evaluated claims can be decided.");
            if (item.Evidence.Count == 0 || item.Evidence.Any(e => e.IsOpen || string.IsNullOrWhiteSpace(e.SourceReference) || string.IsNullOrWhiteSpace(e.ReproducibilityData))) throw new ClaimVerificationTransitionException("Open or incomplete evidence prevents decision.");
            if (cmd.Decision == ClaimVerificationDecision.Verified && !item.Evidence.Any(e => e.Disposition == EvidenceDisposition.Supports && e.Coverage == EvidenceCoverage.Complete && e.Confidence >= 0.8m)) throw new ClaimVerificationTransitionException("Verified requires complete high-confidence supporting evidence.");
            if (cmd.Decision == ClaimVerificationDecision.Refuted && !item.Evidence.Any(e => e.Disposition == EvidenceDisposition.Refutes && e.Confidence >= 0.8m)) throw new ClaimVerificationTransitionException("Refuted requires high-confidence refuting evidence.");
            var status = cmd.Decision switch { ClaimVerificationDecision.Verified => ClaimVerificationStatus.Verified, ClaimVerificationDecision.Refuted => ClaimVerificationStatus.Refuted, ClaimVerificationDecision.Inconclusive => ClaimVerificationStatus.Inconclusive, _ => ClaimVerificationStatus.ResearchRequired };
            var revision = item.Revision + 1; var message = MessageId(cmd.RequestId);
            Execute(c, tx, "UPDATE claim_verifications SET revision=$r,status=$s,decision=$d,decision_reason=$reason,expected_research_revision=$expected,message_id=$m,updated_at_utc=$at WHERE workspace_id=$w AND verification_id=$id;", ("$r", revision), ("$s", status.ToString().ToUpperInvariant()), ("$d", cmd.Decision.ToString().ToUpperInvariant()), ("$reason", cmd.Reason), ("$expected", cmd.ExpectedResearchRevision is null ? DBNull.Value : cmd.ExpectedResearchRevision.Value), ("$m", message.ToString("D")), ("$at", Text(at)), ("$w", item.WorkspaceId), ("$id", item.VerificationId.ToString("D")));
            InsertHistory(c, tx, item.WorkspaceId, item.VerificationId, revision, "DECIDE", cmd.Actor, cmd.Reason, new { cmd.Decision, cmd.ExpectedResearchRevision }, at);
            InsertOutbox(c, tx, message, $"claim.verification.{status.ToString().ToLowerInvariant()}", new { item.WorkspaceId, item.VerificationId, cmd.Decision, cmd.Actor }, at);
            return Require(c, tx, item.WorkspaceId, item.VerificationId);
        }, ct);
    }

    public ValueTask<ClaimVerification> ReopenAsync(ClaimVerificationReopenCommand cmd, DateTimeOffset at, CancellationToken ct = default) => Mutate(cmd.RequestId, cmd.WorkspaceId, cmd.VerificationId, "REOPEN", cmd.RequestFingerprint, Hash(JsonSerializer.Serialize(cmd)), cmd.ExpectedRevision, at, (c, tx, item) =>
    {
        if (string.IsNullOrWhiteSpace(cmd.Reason)) throw new ClaimVerificationValidationException("Reopen reason is required.");
        if (item.Status is ClaimVerificationStatus.Proposed or ClaimVerificationStatus.Evaluated or ClaimVerificationStatus.Stale) throw new ClaimVerificationTransitionException("Verification cannot be reopened from its current state.");
        return Advance(c, tx, item, ClaimVerificationStatus.Proposed, cmd.RequestId, "REOPEN", cmd.Actor, cmd.Reason, new { cmd.Reason }, "claim.verification.reopened", at, clearEvidence: true);
    }, ct);

    public ValueTask<ClaimVerification> MarkStaleAsync(ClaimVerificationStaleCommand cmd, DateTimeOffset at, CancellationToken ct = default) => Mutate(cmd.RequestId, cmd.WorkspaceId, cmd.VerificationId, "STALE", cmd.RequestFingerprint, Hash(JsonSerializer.Serialize(cmd)), cmd.ExpectedRevision, at, (c, tx, item) => MarkStaleCore(c, tx, item, cmd.RequestId, cmd.Reason, cmd.Actor, at), ct);
    public async ValueTask<ClaimVerification?> GetAsync(string workspaceId, Guid verificationId, CancellationToken ct = default) { ct.ThrowIfCancellationRequested(); using var c = _factory.OpenConnection(); return await Task.FromResult(Read(c, null, workspaceId, verificationId)); }
    public async ValueTask DisposeAsync() { if (Interlocked.Exchange(ref _disposed, 1) == 0) await _queue.DisposeAsync().ConfigureAwait(false); }

    private ValueTask<ClaimVerification> Mutate(Guid requestId, string workspace, Guid id, string action, string fingerprint, string hash, long expectedRevision, DateTimeOffset at, Func<SqliteConnection, SqliteTransaction, ClaimVerification, ClaimVerification> mutation, CancellationToken ct) => _queue.ExecuteInTransactionAsync((c, tx, token) => { token.ThrowIfCancellationRequested(); var receipt = ReadReceipt(c, tx, workspace, requestId); if (receipt is not null) { RequireReceipt(receipt, action, workspace, id, fingerprint, hash); return Require(c, tx, workspace, id); } var item = Require(c, tx, workspace, id); if (item.Revision != expectedRevision) throw new ClaimVerificationConflictException("Stale revision."); var result = mutation(c, tx, item); InsertReceipt(c, tx, workspace, requestId, id, action, fingerprint, hash, result.Revision, result.MessageId, at); return result; }, ct);
    private static ClaimVerification Advance(SqliteConnection c, SqliteTransaction tx, ClaimVerification item, ClaimVerificationStatus status, Guid request, string action, string actor, string? reason, object payload, string eventType, DateTimeOffset at, bool clearEvidence = false) { var revision = item.Revision + 1; var message = MessageId(request); if (clearEvidence) Execute(c, tx, "DELETE FROM claim_verification_evidence WHERE workspace_id=$w AND verification_id=$id;", ("$w", item.WorkspaceId), ("$id", item.VerificationId.ToString("D"))); Execute(c, tx, "UPDATE claim_verifications SET revision=$r,status=$s,decision=NULL,decision_reason=$reason,expected_research_revision=NULL,message_id=$m,updated_at_utc=$at WHERE workspace_id=$w AND verification_id=$id;", ("$r", revision), ("$s", status.ToString().ToUpperInvariant()), ("$reason", reason is null ? DBNull.Value : reason), ("$m", message.ToString("D")), ("$at", Text(at)), ("$w", item.WorkspaceId), ("$id", item.VerificationId.ToString("D"))); InsertHistory(c, tx, item.WorkspaceId, item.VerificationId, revision, action, actor, reason, payload, at); InsertOutbox(c, tx, message, eventType, new { item.WorkspaceId, item.VerificationId, Actor = actor }, at); return Require(c, tx, item.WorkspaceId, item.VerificationId); }
    private static ClaimVerification MarkStaleCore(SqliteConnection c, SqliteTransaction tx, ClaimVerification item, Guid request, string reason, string actor, DateTimeOffset at) { if (string.IsNullOrWhiteSpace(reason)) throw new ClaimVerificationValidationException("Stale reason is required."); if (item.Status is ClaimVerificationStatus.Verified or ClaimVerificationStatus.Refuted) throw new ClaimVerificationTransitionException("Final verification cannot be marked stale."); return Advance(c, tx, item, ClaimVerificationStatus.Stale, request, "STALE", actor, reason, new { reason }, "claim.verification.stale", at); }

    private static void ValidateDraft(ClaimVerificationDraft d) { if (d.VerificationId == Guid.Empty || d.ProjectId == Guid.Empty || d.ResearchPlanId == Guid.Empty || d.ClaimId == Guid.Empty || d.ExpectedResearchPlanRevision < 1 || d.Version < 1 || string.IsNullOrWhiteSpace(d.WorkspaceId) || string.IsNullOrWhiteSpace(d.ExpectedResearchPlanDigest) || string.IsNullOrWhiteSpace(d.Location) || string.IsNullOrWhiteSpace(d.RuleSet) || string.IsNullOrWhiteSpace(d.Actor) || string.IsNullOrWhiteSpace(d.SnapshotJson) || string.IsNullOrWhiteSpace(d.RequestFingerprint)) throw new ClaimVerificationValidationException("Complete claim verification draft is required."); }
    private static void ValidateEvidence(IReadOnlyList<ClaimEvidenceDraft> evidence) { if (evidence is null || evidence.Count == 0) throw new ClaimVerificationValidationException("At least one evidence item is required."); if (evidence.Select(x => x.EvidenceId).Distinct().Count() != evidence.Count) throw new ClaimVerificationValidationException("Evidence ids must be unique."); foreach (var e in evidence) { if (e.EvidenceId == Guid.Empty || string.IsNullOrWhiteSpace(e.SourceType) || string.IsNullOrWhiteSpace(e.SourceReference) || string.IsNullOrWhiteSpace(e.Location) || string.IsNullOrWhiteSpace(e.ExtractOrSummary) || string.IsNullOrWhiteSpace(e.ReproducibilityData) || e.Confidence < 0m || e.Confidence > 1m || (e.ValidUntilUtc is not null && e.ValidUntilUtc < e.ConsultedAtUtc)) throw new ClaimVerificationValidationException("Complete reproducible evidence is required."); } }
    private static void RequireAuthority(SqliteConnection c, SqliteTransaction tx, string workspace, Guid project, Guid planId, long expectedRevision, string expectedDigest) { using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "SELECT project_id,revision,status FROM research_plans WHERE workspace_id=$w AND plan_id=$id;"; cmd.Parameters.AddWithValue("$w", workspace); cmd.Parameters.AddWithValue("$id", planId.ToString("D")); using var r = cmd.ExecuteReader(); if (!r.Read()) throw new ClaimVerificationValidationException("Approved research plan authority was not found."); var storedProject = Guid.Parse(r.GetString(0)); var revision = r.GetInt64(1); var status = r.GetString(2); var digest = Hash($"{workspace}:{planId:D}:{revision}:{status}"); if (storedProject != project || revision != expectedRevision || status != "APPROVED" || digest != expectedDigest) throw new ClaimVerificationValidationException("Research plan authority is not exact and approved."); }
    private static bool AuthorityMatches(SqliteConnection c, SqliteTransaction tx, ClaimVerification item) { try { RequireAuthority(c, tx, item.WorkspaceId, item.ProjectId, item.ResearchPlanId, item.ExpectedResearchPlanRevision, item.ExpectedResearchPlanDigest); return true; } catch (ClaimVerificationValidationException) { return false; } }

    private sealed record Receipt(string Workspace, Guid VerificationId, string Action, string Fingerprint, string Hash);
    private static Receipt? ReadReceipt(SqliteConnection c, SqliteTransaction? tx, string w, Guid request) { using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "SELECT workspace_id,verification_id,action,request_fingerprint,payload_hash FROM claim_verification_receipts WHERE workspace_id=$w AND request_id=$r;"; cmd.Parameters.AddWithValue("$w", w); cmd.Parameters.AddWithValue("$r", request.ToString("D")); using var x = cmd.ExecuteReader(); return x.Read() ? new(x.GetString(0), Guid.Parse(x.GetString(1)), x.GetString(2), x.GetString(3), x.GetString(4)) : null; }
    private static void RequireReceipt(Receipt r, string action, string workspace, Guid id, string fingerprint, string hash) { if (r.Workspace != workspace || r.VerificationId != id || r.Action != action || r.Fingerprint != fingerprint || r.Hash != hash) throw new ClaimVerificationConflictException("Request id reused with different payload."); }
    private static ClaimVerification Require(SqliteConnection c, SqliteTransaction? tx, string w, Guid id) => Read(c, tx, w, id) ?? throw new ClaimVerificationValidationException("Claim verification not found.");
    private static ClaimVerification? Read(SqliteConnection c, SqliteTransaction? tx, string w, Guid id) { using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = "SELECT project_id,research_plan_id,expected_research_plan_revision,expected_research_plan_digest,claim_id,claim_type,location,version,rule_set,actor,snapshot_json,revision,status,decision,decision_reason,expected_research_revision,message_id,created_at_utc,updated_at_utc FROM claim_verifications WHERE workspace_id=$w AND verification_id=$id;"; cmd.Parameters.AddWithValue("$w", w); cmd.Parameters.AddWithValue("$id", id.ToString("D")); using var r = cmd.ExecuteReader(); if (!r.Read()) return null; var x = new { Project = Guid.Parse(r.GetString(0)), Plan = Guid.Parse(r.GetString(1)), PlanRevision = r.GetInt64(2), Digest = r.GetString(3), Claim = Guid.Parse(r.GetString(4)), Type = Enum.Parse<ClaimType>(r.GetString(5), true), Location = r.GetString(6), Version = r.GetInt32(7), Rules = r.GetString(8), Actor = r.GetString(9), Snapshot = r.GetString(10), Revision = r.GetInt64(11), Status = Enum.Parse<ClaimVerificationStatus>(r.GetString(12), true), Decision = r.IsDBNull(13) ? (ClaimVerificationDecision?)null : Enum.Parse<ClaimVerificationDecision>(r.GetString(13), true), Reason = r.IsDBNull(14) ? null : r.GetString(14), ExpectedResearch = r.IsDBNull(15) ? (int?)null : r.GetInt32(15), Message = r.IsDBNull(16) ? (Guid?)null : Guid.Parse(r.GetString(16)), Created = DateTimeOffset.Parse(r.GetString(17), CultureInfo.InvariantCulture), Updated = DateTimeOffset.Parse(r.GetString(18), CultureInfo.InvariantCulture) }; r.Close(); var evidence = new List<ClaimEvidence>(); using var q = c.CreateCommand(); q.Transaction = tx; q.CommandText = "SELECT evidence_id,disposition,source_type,source_reference,consulted_at_utc,valid_until_utc,quality,coverage,confidence,location,extract_or_summary,reproducibility_data,is_open FROM claim_verification_evidence WHERE workspace_id=$w AND verification_id=$id ORDER BY evidence_id;"; q.Parameters.AddWithValue("$w", w); q.Parameters.AddWithValue("$id", id.ToString("D")); using var e = q.ExecuteReader(); while (e.Read()) evidence.Add(new(Guid.Parse(e.GetString(0)), Enum.Parse<EvidenceDisposition>(e.GetString(1), true), e.GetString(2), e.GetString(3), DateTimeOffset.Parse(e.GetString(4), CultureInfo.InvariantCulture), e.IsDBNull(5) ? null : DateTimeOffset.Parse(e.GetString(5), CultureInfo.InvariantCulture), Enum.Parse<EvidenceQuality>(e.GetString(6), true), Enum.Parse<EvidenceCoverage>(e.GetString(7), true), decimal.Parse(e.GetString(8), CultureInfo.InvariantCulture), e.GetString(9), e.GetString(10), e.GetString(11), e.GetInt32(12) != 0)); return new(id, x.Project, w, x.Plan, x.PlanRevision, x.Digest, x.Claim, x.Type, x.Location, x.Version, x.Rules, x.Actor, x.Snapshot, x.Revision, x.Status, evidence, x.Decision, x.Reason, x.ExpectedResearch, x.Message, x.Created, x.Updated); }
    private static void ReplaceEvidence(SqliteConnection c, SqliteTransaction tx, string w, Guid id, IReadOnlyList<ClaimEvidenceDraft> evidence) { Execute(c, tx, "DELETE FROM claim_verification_evidence WHERE workspace_id=$w AND verification_id=$id;", ("$w", w), ("$id", id.ToString("D"))); foreach (var e in evidence) Execute(c, tx, "INSERT INTO claim_verification_evidence(workspace_id,verification_id,evidence_id,disposition,source_type,source_reference,consulted_at_utc,valid_until_utc,quality,coverage,confidence,location,extract_or_summary,reproducibility_data,is_open) VALUES($w,$id,$eid,$d,$st,$sr,$consulted,$valid,$q,$c,$confidence,$location,$summary,$repro,$open);", ("$w", w), ("$id", id.ToString("D")), ("$eid", e.EvidenceId.ToString("D")), ("$d", e.Disposition.ToString().ToUpperInvariant()), ("$st", e.SourceType), ("$sr", e.SourceReference), ("$consulted", Text(e.ConsultedAtUtc)), ("$valid", e.ValidUntilUtc is null ? DBNull.Value : Text(e.ValidUntilUtc.Value)), ("$q", e.Quality.ToString().ToUpperInvariant()), ("$c", e.Coverage.ToString().ToUpperInvariant()), ("$confidence", e.Confidence.ToString(CultureInfo.InvariantCulture)), ("$location", e.Location), ("$summary", e.ExtractOrSummary), ("$repro", e.ReproducibilityData), ("$open", e.IsOpen ? 1 : 0)); }
    private static void InsertHistory(SqliteConnection c, SqliteTransaction tx, string w, Guid id, long rev, string action, string actor, string? reason, object payload, DateTimeOffset at) => Execute(c, tx, "INSERT INTO claim_verification_history(workspace_id,verification_id,revision,action,actor,reason,payload_json,occurred_at_utc) VALUES($w,$id,$r,$a,$actor,$reason,$p,$at);", ("$w", w), ("$id", id.ToString("D")), ("$r", rev), ("$a", action), ("$actor", actor), ("$reason", reason is null ? DBNull.Value : reason), ("$p", JsonSerializer.Serialize(payload)), ("$at", Text(at)));
    private static void InsertReceipt(SqliteConnection c, SqliteTransaction tx, string w, Guid request, Guid id, string action, string fingerprint, string hash, long rev, Guid? message, DateTimeOffset at) => Execute(c, tx, "INSERT INTO claim_verification_receipts(workspace_id,request_id,verification_id,action,request_fingerprint,payload_hash,resulting_revision,message_id,created_at_utc) VALUES($w,$r,$id,$a,$f,$h,$v,$m,$at);", ("$w", w), ("$r", request.ToString("D")), ("$id", id.ToString("D")), ("$a", action), ("$f", fingerprint), ("$h", hash), ("$v", rev), ("$m", message is null ? DBNull.Value : message.Value.ToString("D")), ("$at", Text(at)));
    private static void InsertOutbox(SqliteConnection c, SqliteTransaction tx, Guid message, string type, object payload, DateTimeOffset at) => Execute(c, tx, "INSERT INTO outbox_messages(message_id,event_type,schema_version,payload_json,occurred_at_utc,available_at_utc,status,attempts,locked_by,locked_until_utc,last_error,processed_at_utc,created_at_utc) VALUES($id,$t,'1.0',$p,$at,$at,'PENDING',0,NULL,NULL,NULL,NULL,$at);", ("$id", message.ToString("D")), ("$t", type), ("$p", JsonSerializer.Serialize(payload)), ("$at", Text(at)));
    private static void Execute(SqliteConnection c, SqliteTransaction tx, string sql, params (string Name, object Value)[] values) { using var cmd = c.CreateCommand(); cmd.Transaction = tx; cmd.CommandText = sql; foreach (var (n, v) in values) cmd.Parameters.AddWithValue(n, v); cmd.ExecuteNonQuery(); }
    private static Guid MessageId(Guid request) => new(SHA256.HashData(request.ToByteArray()).AsSpan(0, 16));
    private static string Hash(string value) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
    private static string Text(DateTimeOffset value) => value.ToUniversalTime().ToString("O", CultureInfo.InvariantCulture);
}
