using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BookStudio.Application.Authoring;
using Microsoft.Data.Sqlite;

namespace BookStudio.Infrastructure.Persistence.Sqlite.Authoring;

public sealed class SqliteThemesPacingEditingStore : IThemesPacingEditingStore, IAsyncDisposable
{
    private readonly SqliteConnectionFactory _factory;
    private readonly SqliteWriteQueue _queue;
    private int _disposed;
    public SqliteThemesPacingEditingStore(SqliteConnectionFactory factory, int capacity = 64) { _factory = factory ?? throw new ArgumentNullException(nameof(factory)); _queue = new SqliteWriteQueue(factory, capacity); }

    public ValueTask<ThemesPacingReviewCreateResult> CreateAsync(ThemesPacingReviewDraft d, DateTimeOffset at, CancellationToken ct = default)
    {
        ValidateDraft(d);
        var hash = Hash(JsonSerializer.Serialize(new { d.ProjectId,d.WorkspaceId,d.EditorialPlanId,d.DialogueReviewId,d.ExpectedDialogueRevision,d.ExpectedDialogueDigest,d.Version,d.RuleSet,d.Actor,d.SnapshotJson }));
        return _queue.ExecuteInTransactionAsync((c,tx,token) => {
            token.ThrowIfCancellationRequested();
            var existing = Read(c,tx,d.WorkspaceId,d.ReviewId);
            if (existing is not null) { var receipt = ReadReceipt(c,tx,d.WorkspaceId,d.ReviewId) ?? throw new ThemesPacingEditingConflictException("Create receipt missing."); RequireReceipt(receipt,"CREATE",d.WorkspaceId,d.ReviewId,d.RequestFingerprint,hash); return new ThemesPacingReviewCreateResult(existing,true); }
            RequireAuthority(c,tx,d.WorkspaceId,d.ProjectId,d.EditorialPlanId,d.DialogueReviewId,d.ExpectedDialogueRevision,d.ExpectedDialogueDigest);
            var message = MessageId(d.ReviewId);
            Execute(c,tx,"INSERT INTO themes_pacing_reviews(workspace_id,review_id,project_id,editorial_plan_id,dialogue_review_id,expected_dialogue_revision,expected_dialogue_digest,version,rule_set,actor,snapshot_json,revision,status,decision,decision_reason,expected_repair_revision,message_id,created_at_utc,updated_at_utc) VALUES($w,$id,$p,$plan,$source,$r,$digest,$v,$rules,$actor,$snapshot,1,'PROPOSED',NULL,NULL,NULL,$m,$at,$at);",("$w",d.WorkspaceId),("$id",d.ReviewId.ToString("D")),("$p",d.ProjectId.ToString("D")),("$plan",d.EditorialPlanId.ToString("D")),("$source",d.DialogueReviewId.ToString("D")),("$r",d.ExpectedDialogueRevision),("$digest",d.ExpectedDialogueDigest),("$v",d.Version),("$rules",d.RuleSet),("$actor",d.Actor),("$snapshot",d.SnapshotJson),("$m",message.ToString("D")),("$at",Text(at)));
            InsertHistory(c,tx,d.WorkspaceId,d.ReviewId,1,"CREATE",d.Actor,null,new { d.ProjectId,d.EditorialPlanId,d.DialogueReviewId,d.ExpectedDialogueRevision,d.ExpectedDialogueDigest },at);
            InsertReceipt(c,tx,d.WorkspaceId,d.ReviewId,d.ReviewId,"CREATE",d.RequestFingerprint,hash,1,message,at);
            InsertOutbox(c,tx,message,"editorial.themes-pacing.proposed",new { d.WorkspaceId,d.ReviewId,d.ProjectId,d.EditorialPlanId,d.DialogueReviewId,d.Actor },at);
            return new ThemesPacingReviewCreateResult(Require(c,tx,d.WorkspaceId,d.ReviewId),false);
        },ct);
    }

    public ValueTask<ThemesPacingReview> EvaluateAsync(ThemesPacingEvaluateCommand cmd, DateTimeOffset at, CancellationToken ct = default)
    {
        if (cmd.Findings is null || string.IsNullOrWhiteSpace(cmd.Evidence)) throw new ThemesPacingEditingValidationException("Findings and evaluation evidence are required."); ValidateFindings(cmd.Findings);
        return Mutate(cmd.RequestId,cmd.WorkspaceId,cmd.ReviewId,"EVALUATE",cmd.RequestFingerprint,Hash(JsonSerializer.Serialize(new { cmd.WorkspaceId,cmd.ReviewId,cmd.ExpectedRevision,cmd.Findings,cmd.Evidence,cmd.Actor })),cmd.ExpectedRevision,at,(c,tx,r) => {
            if (!AuthorityMatches(c,tx,r)) return MarkStaleCore(c,tx,r,cmd.RequestId,"Dialogue authority drift.",cmd.Actor,at);
            if (r.Status is not (ThemesPacingReviewStatus.Proposed or ThemesPacingReviewStatus.RepairRequired)) throw new ThemesPacingEditingTransitionException("Review cannot be evaluated from its current state.");
            Execute(c,tx,"DELETE FROM themes_pacing_findings WHERE workspace_id=$w AND review_id=$id;",("$w",r.WorkspaceId),("$id",r.ReviewId.ToString("D")));
            foreach (var f in cmd.Findings) Execute(c,tx,"INSERT INTO themes_pacing_findings(workspace_id,review_id,finding_id,area,severity,rule,location,chapter_numbers_json,scene_ids_json,beat_ids_json,spans_json,evidence,is_open) VALUES($w,$id,$fid,$a,$s,$rule,$l,$c,$sc,$b,$sp,$e,$o);",("$w",r.WorkspaceId),("$id",r.ReviewId.ToString("D")),("$fid",f.FindingId.ToString("D")),("$a",f.Area.ToString().ToUpperInvariant()),("$s",f.Severity.ToString().ToUpperInvariant()),("$rule",f.Rule),("$l",f.Location),("$c",JsonSerializer.Serialize(f.ChapterNumbers)),("$sc",JsonSerializer.Serialize(f.SceneIds)),("$b",JsonSerializer.Serialize(f.BeatIds)),("$sp",JsonSerializer.Serialize(f.Spans)),("$e",f.Evidence),("$o",f.IsOpen?1:0));
            var revision=r.Revision+1; var message=MessageId(cmd.RequestId); UpdateReview(c,tx,r,ThemesPacingReviewStatus.Evaluated,revision,null,null,null,message,at); InsertHistory(c,tx,r.WorkspaceId,r.ReviewId,revision,"EVALUATE",cmd.Actor,null,new { cmd.Evidence,FindingCount=cmd.Findings.Count },at); InsertOutbox(c,tx,message,"editorial.themes-pacing.evaluated",new { r.WorkspaceId,r.ReviewId,FindingCount=cmd.Findings.Count,cmd.Actor },at); return Require(c,tx,r.WorkspaceId,r.ReviewId);
        },ct);
    }

    public ValueTask<ThemesPacingReview> DecideAsync(ThemesPacingDecisionCommand cmd, DateTimeOffset at, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(cmd.Reason)) throw new ThemesPacingEditingValidationException("Decision reason is required.");
        return Mutate(cmd.RequestId,cmd.WorkspaceId,cmd.ReviewId,"DECIDE",cmd.RequestFingerprint,Hash(JsonSerializer.Serialize(new { cmd.WorkspaceId,cmd.ReviewId,cmd.ExpectedRevision,cmd.Decision,cmd.Reason,cmd.ExpectedRepairRevision,cmd.Actor })),cmd.ExpectedRevision,at,(c,tx,r) => {
            if (!AuthorityMatches(c,tx,r)) return MarkStaleCore(c,tx,r,cmd.RequestId,"Dialogue authority drift.",cmd.Actor,at);
            if (r.Status != ThemesPacingReviewStatus.Evaluated) throw new ThemesPacingEditingTransitionException("Only an evaluated review can be decided.");
            if (cmd.Decision==ThemesPacingDecision.Approve && r.Findings.Any(f=>f.IsOpen&&f.Severity==ThemesPacingSeverity.Blocking)) throw new ThemesPacingEditingTransitionException("Blocking findings prevent approval.");
            if (cmd.Decision==ThemesPacingDecision.ReturnToRepair && cmd.ExpectedRepairRevision is null) throw new ThemesPacingEditingValidationException("Repair revision is required.");
            var status=cmd.Decision switch { ThemesPacingDecision.Approve=>ThemesPacingReviewStatus.Approved,ThemesPacingDecision.Reject=>ThemesPacingReviewStatus.Rejected,ThemesPacingDecision.ReturnToRepair=>ThemesPacingReviewStatus.RepairRequired,_=>throw new ArgumentOutOfRangeException() }; var revision=r.Revision+1; var message=MessageId(cmd.RequestId); UpdateReview(c,tx,r,status,revision,cmd.Decision,cmd.Reason,cmd.ExpectedRepairRevision,message,at); InsertHistory(c,tx,r.WorkspaceId,r.ReviewId,revision,"DECIDE",cmd.Actor,cmd.Reason,new { cmd.Decision,cmd.ExpectedRepairRevision },at); InsertOutbox(c,tx,message,cmd.Decision switch { ThemesPacingDecision.Approve=>"editorial.themes-pacing.approved",ThemesPacingDecision.Reject=>"editorial.themes-pacing.rejected",_=>"editorial.themes-pacing.repair-required" },new { r.WorkspaceId,r.ReviewId,cmd.Decision,cmd.Reason,cmd.Actor },at); return Require(c,tx,r.WorkspaceId,r.ReviewId);
        },ct);
    }

    public ValueTask<ThemesPacingReview> ReopenAsync(ThemesPacingReopenCommand cmd, DateTimeOffset at, CancellationToken ct = default) => Mutate(cmd.RequestId,cmd.WorkspaceId,cmd.ReviewId,"REOPEN",cmd.RequestFingerprint,Hash(JsonSerializer.Serialize(cmd)),cmd.ExpectedRevision,at,(c,tx,r)=>{ if(string.IsNullOrWhiteSpace(cmd.Reason)) throw new ThemesPacingEditingValidationException("Reopen reason is required."); if(r.Status is not (ThemesPacingReviewStatus.Approved or ThemesPacingReviewStatus.Rejected or ThemesPacingReviewStatus.Stale)) throw new ThemesPacingEditingTransitionException("Review cannot be reopened from its current state."); var rev=r.Revision+1; var m=MessageId(cmd.RequestId); UpdateReview(c,tx,r,ThemesPacingReviewStatus.Proposed,rev,null,null,null,m,at); InsertHistory(c,tx,r.WorkspaceId,r.ReviewId,rev,"REOPEN",cmd.Actor,cmd.Reason,new { cmd.Reason },at); InsertOutbox(c,tx,m,"editorial.themes-pacing.reopened",new { r.WorkspaceId,r.ReviewId,cmd.Reason,cmd.Actor },at); return Require(c,tx,r.WorkspaceId,r.ReviewId); },ct);
    public ValueTask<ThemesPacingReview> MarkStaleAsync(ThemesPacingStaleCommand cmd, DateTimeOffset at, CancellationToken ct = default) => Mutate(cmd.RequestId,cmd.WorkspaceId,cmd.ReviewId,"STALE",cmd.RequestFingerprint,Hash(JsonSerializer.Serialize(cmd)),cmd.ExpectedRevision,at,(c,tx,r)=>MarkStaleCore(c,tx,r,cmd.RequestId,cmd.Reason,cmd.Actor,at),ct);
    public async ValueTask<ThemesPacingReview?> GetAsync(string workspaceId, Guid reviewId, CancellationToken ct = default) { ct.ThrowIfCancellationRequested(); using var c=_factory.OpenConnection(); return await Task.FromResult(Read(c,null,workspaceId,reviewId)); }
    public async ValueTask DisposeAsync() { if(Interlocked.Exchange(ref _disposed,1)==0) await _queue.DisposeAsync().ConfigureAwait(false); }

    private ValueTask<ThemesPacingReview> Mutate(Guid requestId,string workspace,Guid reviewId,string action,string fingerprint,string hash,long expectedRevision,DateTimeOffset at,Func<SqliteConnection,SqliteTransaction,ThemesPacingReview,ThemesPacingReview> mutate,CancellationToken ct)=>_queue.ExecuteInTransactionAsync((c,tx,token)=>{ token.ThrowIfCancellationRequested(); var receipt=ReadReceipt(c,tx,workspace,requestId); if(receipt is not null){RequireReceipt(receipt,action,workspace,reviewId,fingerprint,hash); return Require(c,tx,workspace,reviewId);} var r=Require(c,tx,workspace,reviewId); if(r.Revision!=expectedRevision) throw new ThemesPacingEditingConflictException("Stale revision."); var result=mutate(c,tx,r); InsertReceipt(c,tx,workspace,requestId,reviewId,action,fingerprint,hash,result.Revision,result.MessageId,at); return result;},ct);
    private static ThemesPacingReview MarkStaleCore(SqliteConnection c,SqliteTransaction tx,ThemesPacingReview r,Guid requestId,string reason,string actor,DateTimeOffset at){ if(string.IsNullOrWhiteSpace(reason)) throw new ThemesPacingEditingValidationException("Stale reason is required."); if(r.Status==ThemesPacingReviewStatus.Approved) throw new ThemesPacingEditingTransitionException("Approved review must be reopened before stale transition."); var rev=r.Revision+1; var m=MessageId(requestId); UpdateReview(c,tx,r,ThemesPacingReviewStatus.Stale,rev,null,reason,null,m,at); InsertHistory(c,tx,r.WorkspaceId,r.ReviewId,rev,"STALE",actor,reason,new { reason },at); InsertOutbox(c,tx,m,"editorial.themes-pacing.stale",new { r.WorkspaceId,r.ReviewId,r.ProjectId,Reason=reason,Actor=actor },at); return Require(c,tx,r.WorkspaceId,r.ReviewId); }
    private static void ValidateDraft(ThemesPacingReviewDraft d){ if(d.ReviewId==Guid.Empty||d.ProjectId==Guid.Empty||d.EditorialPlanId==Guid.Empty||d.DialogueReviewId==Guid.Empty||d.ExpectedDialogueRevision<1||d.Version<1||string.IsNullOrWhiteSpace(d.WorkspaceId)||string.IsNullOrWhiteSpace(d.ExpectedDialogueDigest)||string.IsNullOrWhiteSpace(d.RuleSet)||string.IsNullOrWhiteSpace(d.Actor)||string.IsNullOrWhiteSpace(d.SnapshotJson)||string.IsNullOrWhiteSpace(d.RequestFingerprint)) throw new ThemesPacingEditingValidationException("Complete themes/pacing review is required."); }
    private static void ValidateFindings(IReadOnlyList<ThemesPacingFindingDraft> fs){ if(fs.Select(x=>x.FindingId).Distinct().Count()!=fs.Count) throw new ThemesPacingEditingValidationException("Finding ids must be unique."); foreach(var f in fs) if(f.FindingId==Guid.Empty||string.IsNullOrWhiteSpace(f.Rule)||string.IsNullOrWhiteSpace(f.Location)||string.IsNullOrWhiteSpace(f.Evidence)||f.ChapterNumbers is null||f.SceneIds is null||f.BeatIds is null||f.Spans is null||f.ChapterNumbers.Any(x=>x<1)||f.SceneIds.Any(string.IsNullOrWhiteSpace)||f.BeatIds.Any(string.IsNullOrWhiteSpace)||f.Spans.Any(string.IsNullOrWhiteSpace)) throw new ThemesPacingEditingValidationException("Complete finding evidence is required."); }
    private static void RequireAuthority(SqliteConnection c,SqliteTransaction tx,string workspace,Guid project,Guid plan,Guid source,long expectedRevision,string expectedDigest){ using var cmd=c.CreateCommand(); cmd.Transaction=tx; cmd.CommandText="SELECT r.project_id,r.editorial_plan_id,r.revision,r.status,n.status FROM dialogue_reviews r JOIN editorial_pass_nodes n ON n.workspace_id=r.workspace_id AND n.plan_id=r.editorial_plan_id WHERE r.workspace_id=$w AND r.review_id=$id AND n.pass_kind='THEMESPACING';"; cmd.Parameters.AddWithValue("$w",workspace); cmd.Parameters.AddWithValue("$id",source.ToString("D")); using var rd=cmd.ExecuteReader(); if(!rd.Read()) throw new ThemesPacingEditingValidationException("Approved dialogue authority was not found."); var p=Guid.Parse(rd.GetString(0)); var pl=Guid.Parse(rd.GetString(1)); var rev=rd.GetInt64(2); var status=rd.GetString(3); var node=rd.GetString(4); var digest=Hash($"{workspace}:{source:D}:{rev}:{status}"); if(p!=project||pl!=plan||rev!=expectedRevision||status!="APPROVED"||node!="READY"||!CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(digest),Encoding.UTF8.GetBytes(expectedDigest))) throw new ThemesPacingEditingValidationException("Dialogue authority is not approved, exact, current, or dependency-ready."); }
    private static bool AuthorityMatches(SqliteConnection c,SqliteTransaction tx,ThemesPacingReview r){ try{RequireAuthority(c,tx,r.WorkspaceId,r.ProjectId,r.EditorialPlanId,r.DialogueReviewId,r.ExpectedDialogueRevision,r.ExpectedDialogueDigest);return true;}catch(ThemesPacingEditingValidationException){return false;} }
    private sealed record Receipt(string Workspace,Guid ReviewId,string Action,string Fingerprint,string Hash);
    private static Receipt? ReadReceipt(SqliteConnection c,SqliteTransaction? tx,string workspace,Guid request){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT workspace_id,review_id,action,request_fingerprint,payload_hash FROM themes_pacing_receipts WHERE workspace_id=$w AND request_id=$r;";cmd.Parameters.AddWithValue("$w",workspace);cmd.Parameters.AddWithValue("$r",request.ToString("D"));using var rd=cmd.ExecuteReader();return rd.Read()?new(rd.GetString(0),Guid.Parse(rd.GetString(1)),rd.GetString(2),rd.GetString(3),rd.GetString(4)):null;}
    private static void RequireReceipt(Receipt r,string action,string workspace,Guid review,string fingerprint,string hash){if(r.Workspace!=workspace||r.ReviewId!=review||r.Action!=action||r.Fingerprint!=fingerprint||r.Hash!=hash) throw new ThemesPacingEditingConflictException("Request id reused with different payload.");}
    private static ThemesPacingReview Require(SqliteConnection c,SqliteTransaction? tx,string workspace,Guid id)=>Read(c,tx,workspace,id)??throw new ThemesPacingEditingValidationException("Themes/pacing review not found.");
    private static ThemesPacingReview? Read(SqliteConnection c,SqliteTransaction? tx,string workspace,Guid id){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT project_id,editorial_plan_id,dialogue_review_id,expected_dialogue_revision,expected_dialogue_digest,version,rule_set,actor,snapshot_json,revision,status,decision,decision_reason,expected_repair_revision,message_id,created_at_utc,updated_at_utc FROM themes_pacing_reviews WHERE workspace_id=$w AND review_id=$id;";cmd.Parameters.AddWithValue("$w",workspace);cmd.Parameters.AddWithValue("$id",id.ToString("D"));using var rd=cmd.ExecuteReader();if(!rd.Read())return null;var project=Guid.Parse(rd.GetString(0));var plan=Guid.Parse(rd.GetString(1));var source=Guid.Parse(rd.GetString(2));var sourceRev=rd.GetInt64(3);var digest=rd.GetString(4);var version=rd.GetInt32(5);var rules=rd.GetString(6);var actor=rd.GetString(7);var snapshot=rd.GetString(8);var rev=rd.GetInt64(9);var status=Enum.Parse<ThemesPacingReviewStatus>(rd.GetString(10).Replace("_",string.Empty),true);ThemesPacingDecision? decision=rd.IsDBNull(11)?null:Enum.Parse<ThemesPacingDecision>(rd.GetString(11).Replace("_",string.Empty),true);var reason=rd.IsDBNull(12)?null:rd.GetString(12);int? repair=rd.IsDBNull(13)?null:rd.GetInt32(13);Guid? message=rd.IsDBNull(14)?null:Guid.Parse(rd.GetString(14));var created=DateTimeOffset.Parse(rd.GetString(15),CultureInfo.InvariantCulture);var updated=DateTimeOffset.Parse(rd.GetString(16),CultureInfo.InvariantCulture);rd.Close();var fs=new List<ThemesPacingFinding>();using var f=c.CreateCommand();f.Transaction=tx;f.CommandText="SELECT finding_id,area,severity,rule,location,chapter_numbers_json,scene_ids_json,beat_ids_json,spans_json,evidence,is_open FROM themes_pacing_findings WHERE workspace_id=$w AND review_id=$id ORDER BY finding_id;";f.Parameters.AddWithValue("$w",workspace);f.Parameters.AddWithValue("$id",id.ToString("D"));using var fr=f.ExecuteReader();while(fr.Read())fs.Add(new(Guid.Parse(fr.GetString(0)),Enum.Parse<ThemesPacingFindingArea>(fr.GetString(1),true),Enum.Parse<ThemesPacingSeverity>(fr.GetString(2),true),fr.GetString(3),fr.GetString(4),JsonSerializer.Deserialize<List<int>>(fr.GetString(5))??[],JsonSerializer.Deserialize<List<string>>(fr.GetString(6))??[],JsonSerializer.Deserialize<List<string>>(fr.GetString(7))??[],JsonSerializer.Deserialize<List<string>>(fr.GetString(8))??[],fr.GetString(9),fr.GetInt32(10)==1));return new(id,project,workspace,plan,source,sourceRev,digest,version,rules,actor,snapshot,rev,status,fs,decision,reason,repair,message,created,updated);}
    private static void UpdateReview(SqliteConnection c,SqliteTransaction tx,ThemesPacingReview r,ThemesPacingReviewStatus status,long revision,ThemesPacingDecision? decision,string? reason,int? repair,Guid message,DateTimeOffset at)=>Execute(c,tx,"UPDATE themes_pacing_reviews SET revision=$r,status=$s,decision=$d,decision_reason=$reason,expected_repair_revision=$repair,message_id=$m,updated_at_utc=$at WHERE workspace_id=$w AND review_id=$id;",("$r",revision),("$s",Db(status)),("$d",decision is null?DBNull.Value:Db(decision.Value)),("$reason",reason is null?DBNull.Value:reason),("$repair",repair is null?DBNull.Value:repair.Value),("$m",message.ToString("D")),("$at",Text(at)),("$w",r.WorkspaceId),("$id",r.ReviewId.ToString("D")));
    private static void InsertHistory(SqliteConnection c,SqliteTransaction tx,string w,Guid id,long rev,string action,string actor,string? reason,object payload,DateTimeOffset at)=>Execute(c,tx,"INSERT INTO themes_pacing_history(workspace_id,review_id,revision,action,actor,reason,payload_json,occurred_at_utc) VALUES($w,$id,$r,$a,$actor,$reason,$p,$at);",("$w",w),("$id",id.ToString("D")),("$r",rev),("$a",action),("$actor",actor),("$reason",reason is null?DBNull.Value:reason),("$p",JsonSerializer.Serialize(payload)),("$at",Text(at)));
    private static void InsertReceipt(SqliteConnection c,SqliteTransaction tx,string w,Guid req,Guid id,string action,string fp,string hash,long rev,Guid? message,DateTimeOffset at)=>Execute(c,tx,"INSERT INTO themes_pacing_receipts(workspace_id,request_id,review_id,action,request_fingerprint,payload_hash,resulting_revision,message_id,created_at_utc) VALUES($w,$req,$id,$a,$f,$h,$r,$m,$at);",("$w",w),("$req",req.ToString("D")),("$id",id.ToString("D")),("$a",action),("$f",fp),("$h",hash),("$r",rev),("$m",message is null?DBNull.Value:message.Value.ToString("D")),("$at",Text(at)));
    private static void InsertOutbox(SqliteConnection c,SqliteTransaction tx,Guid id,string type,object payload,DateTimeOffset at)=>Execute(c,tx,"INSERT INTO outbox_messages(message_id,event_type,schema_version,payload_json,occurred_at_utc,available_at_utc,status,attempts,locked_by,locked_until_utc,last_error,processed_at_utc,created_at_utc) VALUES($id,$t,'1.0',$p,$at,$at,'PENDING',0,NULL,NULL,NULL,NULL,$at);",("$id",id.ToString("D")),("$t",type),("$p",JsonSerializer.Serialize(payload)),("$at",Text(at)));
    private static void Execute(SqliteConnection c,SqliteTransaction tx,string sql,params (string Name,object Value)[] values){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=sql;foreach(var(n,v)in values)cmd.Parameters.AddWithValue(n,v);cmd.ExecuteNonQuery();}
    private static string Db(ThemesPacingReviewStatus s)=>s==ThemesPacingReviewStatus.RepairRequired?"REPAIR_REQUIRED":s.ToString().ToUpperInvariant(); private static string Db(ThemesPacingDecision d)=>d==ThemesPacingDecision.ReturnToRepair?"RETURN_TO_REPAIR":d.ToString().ToUpperInvariant();
    private static Guid MessageId(Guid request)=>new(SHA256.HashData(request.ToByteArray()).AsSpan(0,16)); private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant(); private static string Text(DateTimeOffset value)=>value.ToUniversalTime().ToString("O",CultureInfo.InvariantCulture);
}
