<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>BookStudio.Tests.Api</AssemblyName>
    <RootNamespace>BookStudio.Tests.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/BookStudio.ControlCenter/BookStudio.ControlCenter.csproj" />
  </ItemGroup>
</Project>
